spring:
  application:
    name: url-shortener

  datasource:
    url: ${db_url}
    username: ${db_user}
    password: ${db_password}

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${redis_host}
      port: ${redis_port}
